#ifndef SHOW_FILE_STRINGS
#define SHOW_FILE_STRINGS

#define  SHOW_FILE_HEADER  \
   "<!-- # This file is generated by Starvax Meteor Player"\
   "     # Please do not edit manually-->"

#define  PLAYLIST_LEGACY_START_TAG   "<!--PLAYLIST>"
#define  PLAYLIST_LEGACY_END_TAG     "<PLAYLIST-->"

#define  PLAYLIST_LINE_A_START_TAG   "<!--PLAYLIST_LINE_A>"
#define  PLAYLIST_LINE_A_END_TAG     "<PLAYLIST_LINE_A-->"

#define  PLAYLIST_LINE_B_START_TAG   "<!--PLAYLIST_LINE_B>"
#define  PLAYLIST_LINE_B_END_TAG     "<PLAYLIST_LINE_B-->"

#define  LIGHTSET_START_TAG   "<!--LIGHTSET>"
#define  LIGHTSET_END_TAG     "<LIGHTSET-->"

#define  DEPRECATED_SEQUENCE_START_TAG   "<!--SEQUENCE>"
#define  DEPRECATED_SEQUENCE_END_TAG     "<SEQUENCE-->"

#define  SEQUENCER_START_TAG   "<!--SEQUENCER>"
#define  SEQUENCER_END_TAG     "<SEQUENCER-->"

#define  HTML_START_TAG       "<!DOCTYPE"

#endif // SHOW_FILE_STRINGS
